# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.14 # https://pyreadiness.org/3.10
  - robocorp-truststore=0.8.0 # https://pypi.org/project/robocorp-truststore/
  - pip=24.0 # https://pip.pypa.io/en/stable/news
  - nodejs=22.13.0
  # - robocorp==2.1.3             # https://pypi.org/project/robocorp
  # - robocorp-browser==2.3.4     # https://pypi.org/project/robocorp-browser
  - pip:
      - robotframework==7.2.2
      - robotframework-browser==19.3.1
      - rpaframework==30.0.1 # https://rpaframework.org/releasenotes.html
      - requests==2.32.3 # https://pypi.org/project/requests
rccPostInstall:
  - rfbrowser init # Initialize Playwright
